---
- name: Implementing loops
  hosts: all
  tasks:
   - name: Install s.w applications
     apt:
      name: "{{item}}"
      state: present
      update_cache: no
     with_items:
      - tree
      - maven
      - git
      - openjdk-8-jdk
...
